name: CI/CD Pipeline for .NET Console App

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Cache .NET dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx"

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
      if: always()

    - name: Publish
      run: dotnet publish --configuration Release -o ./publish

    - name: Compress Artifacts
      run: Compress-Archive -Path .\publish\* -DestinationPath ConApp1Net8ActionBuildTest-windows.zip

    - name: Clean Up (Optional)
      run: Remove-Item -Recurse -Force ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConApp1Net8ActionBuildTest-windows
        path: ConApp1Net8ActionBuildTest-windows.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ConApp1Net8ActionBuildTest-windows
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ConApp1Net8ActionBuildTest_BootySmells_v${{ github.run_number }}
        name: ConApp1Net8ActionBuildTest_BootySmells_Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: ./artifacts/ConApp1Net8ActionBuildTest-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}